### ISSUE TITLE
Manage the Repository

### ISSUE THREAD

**Issue by noahaus** [noahaus/CPPHelloWorld#2]
Greetings Neira, 

To get a feel for github, I helped put together a simple example of what its like to collaborate. 
Its pretty simple stuff too, but may lead to some good learning.

- [x] First, you need to review and summarize the open pull request. this one looks to merge 'noah-dev' into 'main'
- [x] Second, after the merge, then create a pull-request for 'neira-dev' to 'main'. You will find this one won't be as straight forward. 

After we do this I think you will understand the crucial aspects of github. everything else will most likely taught at a higher level too.

**Comment by noahaus** [comment]
We will both be learning through this process. Especially for the second task - I am including a link here that I hope will be useful:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by NeiraIbrahimovic** [comment]
Okay Noah, thank you for the assignment! I will get this done by the end of the work day. :)

**Comment by NeiraIbrahimovic** [comment]
All done!
